version: "3.9"

services:
  frontend:
    container_name: devouzer_react
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - 3000:3000